name: Multi-Platform Test (lib only)

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'az_analyze_image/**'

  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4

    - name: Install Rust
      run: |
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
      shell: bash

    - name: Run tests
      run: cargo test --release --lib
      shell: bash
      env:
        # mock key and endpoint (https://{}.cognitiveservices.azure.com/)
        CV_KEY: 679ddc27f1d441c888314eba5c3dc030
        CV_ENDPOINT: https://.cognitiveservices.azure.com/
